package me.newsong.domain.entity;

public class CountryDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_name
     *
     * @mbggenerated
     */
    private String countryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated
     */
    public CountryDO(Long id, String countryName) {
        this.id = id;
        this.countryName = countryName;
    }
    
    public CountryDO(String countryName){
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbggenerated
     */
    public CountryDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_name
     *
     * @return the value of country.country_name
     *
     * @mbggenerated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_name
     *
     * @param countryName the value for country.country_name
     *
     * @mbggenerated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }


    @Override
    public String toString() {
        return "CountryDO{" +
                "id=" + id +
                ", countryName='" + countryName + '\'' +
                '}';
    }
}