package me.newsong.domain.entity;

public class DirectorDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column director.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column director.director_name
     *
     * @mbggenerated
     */
    private String directorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    public DirectorDO(Long id, String directorName) {
        this.id = id;
        this.directorName = directorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    public DirectorDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column director.id
     *
     * @return the value of director.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column director.id
     *
     * @param id the value for director.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column director.director_name
     *
     * @return the value of director.director_name
     *
     * @mbggenerated
     */
    public String getDirectorName() {
        return directorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column director.director_name
     *
     * @param directorName the value for director.director_name
     *
     * @mbggenerated
     */
    public void setDirectorName(String directorName) {
        this.directorName = directorName == null ? null : directorName.trim();
    }

    @Override
    public String toString() {
        return "DirectorDO{" +
                "id=" + id +
                ", directorName='" + directorName + '\'' +
                '}';
    }
}