package me.newsong.domain.entity;

public class MovieWriterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_writer.movie_id
     *
     * @mbggenerated
     */
    private Long movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_writer.writer_id
     *
     * @mbggenerated
     */
    private Long writerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_writer
     *
     * @mbggenerated
     */
    public MovieWriterKey(Long movieId, Long writerId) {
        this.movieId = movieId;
        this.writerId = writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_writer
     *
     * @mbggenerated
     */
    public MovieWriterKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_writer.movie_id
     *
     * @return the value of movie_writer.movie_id
     *
     * @mbggenerated
     */
    public Long getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_writer.movie_id
     *
     * @param movieId the value for movie_writer.movie_id
     *
     * @mbggenerated
     */
    public void setMovieId(Long movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_writer.writer_id
     *
     * @return the value of movie_writer.writer_id
     *
     * @mbggenerated
     */
    public Long getWriterId() {
        return writerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_writer.writer_id
     *
     * @param writerId the value for movie_writer.writer_id
     *
     * @mbggenerated
     */
    public void setWriterId(Long writerId) {
        this.writerId = writerId;
    }
}