package me.newsong.domain.entity;

public class MovieLanguageKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_language.movie_id
     *
     * @mbggenerated
     */
    private Long movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_language.language_id
     *
     * @mbggenerated
     */
    private Long languageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_language
     *
     * @mbggenerated
     */
    public MovieLanguageKey(Long movieId, Long languageId) {
        this.movieId = movieId;
        this.languageId = languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_language
     *
     * @mbggenerated
     */
    public MovieLanguageKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_language.movie_id
     *
     * @return the value of movie_language.movie_id
     *
     * @mbggenerated
     */
    public Long getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_language.movie_id
     *
     * @param movieId the value for movie_language.movie_id
     *
     * @mbggenerated
     */
    public void setMovieId(Long movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_language.language_id
     *
     * @return the value of movie_language.language_id
     *
     * @mbggenerated
     */
    public Long getLanguageId() {
        return languageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_language.language_id
     *
     * @param languageId the value for movie_language.language_id
     *
     * @mbggenerated
     */
    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
    }
}