package me.newsong.domain.entity;

public class MovieDirectorKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_director.movie_id
     *
     * @mbggenerated
     */
    private Long movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_director.director_id
     *
     * @mbggenerated
     */
    private Long directorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_director
     *
     * @mbggenerated
     */
    public MovieDirectorKey(Long movieId, Long directorId) {
        this.movieId = movieId;
        this.directorId = directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_director
     *
     * @mbggenerated
     */
    public MovieDirectorKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_director.movie_id
     *
     * @return the value of movie_director.movie_id
     *
     * @mbggenerated
     */
    public Long getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_director.movie_id
     *
     * @param movieId the value for movie_director.movie_id
     *
     * @mbggenerated
     */
    public void setMovieId(Long movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_director.director_id
     *
     * @return the value of movie_director.director_id
     *
     * @mbggenerated
     */
    public Long getDirectorId() {
        return directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_director.director_id
     *
     * @param directorId the value for movie_director.director_id
     *
     * @mbggenerated
     */
    public void setDirectorId(Long directorId) {
        this.directorId = directorId;
    }
}