package me.newsong.domain.entity;

public class MovieTagKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_tag.movie_id
     *
     * @mbggenerated
     */
    private Long movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_tag.movie_tag
     *
     * @mbggenerated
     */
    private Long movieTag;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_tag
     *
     * @mbggenerated
     */
    public MovieTagKey(Long movieId, Long movieTag) {
        this.movieId = movieId;
        this.movieTag = movieTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_tag
     *
     * @mbggenerated
     */
    public MovieTagKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_tag.movie_id
     *
     * @return the value of movie_tag.movie_id
     *
     * @mbggenerated
     */
    public Long getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_tag.movie_id
     *
     * @param movieId the value for movie_tag.movie_id
     *
     * @mbggenerated
     */
    public void setMovieId(Long movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_tag.movie_tag
     *
     * @return the value of movie_tag.movie_tag
     *
     * @mbggenerated
     */
    public Long getMovieTag() {
        return movieTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_tag.movie_tag
     *
     * @param movieTag the value for movie_tag.movie_tag
     *
     * @mbggenerated
     */
    public void setMovieTag(Long movieTag) {
        this.movieTag = movieTag;
    }
}