package me.newsong.domain.entity;

import java.time.LocalDate;
import java.util.List;

public class RemoteMovieInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_id
     *
     * @mbggenerated
     */
    private String movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.poster_url
     *
     * @mbggenerated
     */
    private String posterUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.release_time
     *
     * @mbggenerated
     */
    private LocalDate releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.imdb_score
     *
     * @mbggenerated
     */
    private Double imdbScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.duration
     *
     * @mbggenerated
     */
    private Integer duration;
    private List<DirectorDO> directors;
    private List<WriterDO> writers;
    private List<ActorDO> actors;
    private List<LanguageDO> languages;
    private List<CountryDO> countries;
    private List<MovieTagDO> tags;
    private Movie movie = new Movie();
    private Integer doubanReviewTime;
    private Integer imdbReviewTime;
    private Double doubanScore;
    private Integer gross;
    private Boolean isDisplay;
    private Long movieRecommendId;
    
    
    public RemoteMovieInfoDO(Long id, String movieId, String posterUrl, String name, LocalDate releaseTime, String summary, Double imdbScore, Integer duration) {
        this.id = id;
        this.movieId = movieId;
        this.posterUrl = posterUrl;
        this.name = name;
        this.releaseTime = releaseTime;
        this.summary = summary;
        this.imdbScore = imdbScore;
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    public RemoteMovieInfoDO(Long id, String movieId, String posterUrl, String name, LocalDate releaseTime, String summary, Double imdbScore, Integer duration, List<DirectorDO> directors, List<WriterDO> writers, List<ActorDO> actors, List<LanguageDO> languages, List<CountryDO> countries, List<MovieTagDO> tags) {
        this.id = id;
        this.movieId = movieId;
        this.posterUrl = posterUrl;
        this.name = name;
        this.releaseTime = releaseTime;
        this.summary = summary;
        this.imdbScore = imdbScore;
        this.duration = duration;
        this.directors = directors;
        this.writers = writers;
        this.actors = actors;
        this.languages = languages;
        this.countries = countries;
        this.tags = tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    public RemoteMovieInfoDO() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.id
     *
     * @return the value of movie.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.id
     *
     * @param id the value for movie.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movie_id
     *
     * @return the value of movie.movie_id
     * @mbggenerated
     */
    public String getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movie_id
     *
     * @param movieId the value for movie.movie_id
     * @mbggenerated
     */
    public void setMovieId(String movieId) {
        this.movieId = movieId == null ? null : movieId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.poster_url
     *
     * @return the value of movie.poster_url
     * @mbggenerated
     */
    public String getPosterUrl() {
        return posterUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.poster_url
     *
     * @param posterUrl the value for movie.poster_url
     * @mbggenerated
     */
    public void setPosterUrl(String posterUrl) {
        this.posterUrl = posterUrl == null ? null : posterUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.name
     *
     * @return the value of movie.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.name
     *
     * @param name the value for movie.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.release_time
     *
     * @return the value of movie.release_time
     * @mbggenerated
     */
    public LocalDate getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.release_time
     *
     * @param releaseTime the value for movie.release_time
     * @mbggenerated
     */
    public void setReleaseTime(LocalDate releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.summary
     *
     * @return the value of movie.summary
     * @mbggenerated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.summary
     *
     * @param summary the value for movie.summary
     * @mbggenerated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.imdb_score
     *
     * @return the value of movie.imdb_score
     * @mbggenerated
     */
    public Double getImdbScore() {
        return imdbScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.imdb_score
     *
     * @param imdbScore the value for movie.imdb_score
     * @mbggenerated
     */
    public void setImdbScore(Double imdbScore) {
        this.imdbScore = imdbScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.duration
     *
     * @return the value of movie.duration
     * @mbggenerated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.duration
     *
     * @param duration the value for movie.duration
     * @mbggenerated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public List<DirectorDO> getDirectors() {
        return directors;
    }

    public void setDirectors(List<DirectorDO> directors) {
        this.directors = directors;
    }

    public List<WriterDO> getWriters() {
        return writers;
    }

    public void setWriters(List<WriterDO> writers) {
        this.writers = writers;
    }

    public List<ActorDO> getActors() {
        return actors;
    }

    public void setActors(List<ActorDO> actors) {
        this.actors = actors;
    }

    public List<LanguageDO> getLanguages() {
        return languages;
    }

    public void setLanguages(List<LanguageDO> languages) {
        this.languages = languages;
    }

    public List<CountryDO> getCountries() {
        return countries;
    }

    public void setCountries(List<CountryDO> countries) {
        this.countries = countries;
    }

    public List<MovieTagDO> getTags() {
        return tags;
    }

    public void setTags(List<MovieTagDO> tags) {
        this.tags = tags;
    }

    public Movie getMovie() {
        return movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    public Integer getDoubanReviewTime() {
        return doubanReviewTime;
    }

    public void setDoubanReviewTime(Integer doubanReviewTime) {
        this.doubanReviewTime = doubanReviewTime;
    }

    public Integer getImdbReviewTime() {
        return imdbReviewTime;
    }

    public void setImdbReviewTime(Integer imdbReviewTime) {
        this.imdbReviewTime = imdbReviewTime;
    }

    public Double getDoubanScore() {
        return doubanScore;
    }

    public void setDoubanScore(Double doubanScore) {
        this.doubanScore = doubanScore;
    }

    public Integer getGross() {
        return gross;
    }

    public void setGross(Integer gross) {
        this.gross = gross;
    }

    public Boolean getDisplay() {
        return isDisplay;
    }

    public void setDisplay(Boolean display) {
        isDisplay = display;
    }

    public Long getMovieRecommendId() {
        return movieRecommendId;
    }

    public void setMovieRecommendId(Long movieRecommendId) {
        this.movieRecommendId = movieRecommendId;
    }

    @Override
    public String toString() {
        return "RemoteMovieInfoDO{" +
                "id=" + id +
                ", movieId='" + movieId + '\'' +
                ", posterUrl='" + posterUrl + '\'' +
                ", name='" + name + '\'' +
                ", releaseTime=" + releaseTime +
                ", summary='" + summary + '\'' +
                ", imdbScore=" + imdbScore +
                ", duration=" + duration +
                ", directors=" + directors +
                ", writers=" + writers +
                ", actors=" + actors +
                ", languages=" + languages +
                ", countries=" + countries +
                ", tags=" + tags +
                ", movie=" + movie +
                ", doubanReviewTime=" + doubanReviewTime +
                ", imdbReviewTime=" + imdbReviewTime +
                ", doubanScore=" + doubanScore +
                ", gross=" + gross +
                ", isDisplay=" + isDisplay +
                ", movieRecommendId=" + movieRecommendId +
                '}';
    }
}