package me.newsong.domain.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateSerializer;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.List;
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RemoteMovieInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movie_id
     *
     * @mbggenerated
     */
    private String movieId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.poster_url
     *
     * @mbggenerated
     */
    private String posterUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.release_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    @JsonSerialize(using = LocalDateSerializer.class)
    @JsonDeserialize(using = LocalDateDeserializer.class)
    private LocalDate releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.summary
     *
     * @mbggenerated
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.imdb_score
     *
     * @mbggenerated
     */
    private Double imdbScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.duration
     *
     * @mbggenerated
     */
    private Integer duration;
    private List<DirectorDO> directors;
    private List<WriterDO> writers;
    private List<ActorDO> actors;
    private List<LanguageDO> languages;
    private List<CountryDO> countries;
    private List<MovieTagDO> tags;
    private Movie movie = new Movie();
    private Integer doubanReviewTime;
    private Integer imdbReviewTime;
    private Double doubanScore;
    private Integer gross;
    private Long movieRecommendId;
    private Integer num_user_for_reviews;
    private Integer num_critic_for_reviews;
    private Long budget;
        
    public RemoteMovieInfoDO(Long id, String movieId, String posterUrl, String name, LocalDate releaseTime, String summary, Double imdbScore, Integer duration) {
        this.id = id;
        this.movieId = movieId;
        this.posterUrl = posterUrl;
        this.name = name;
        this.releaseTime = releaseTime;
        this.summary = summary;
        this.imdbScore = imdbScore;
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie
     *
     * @mbggenerated
     */
    public RemoteMovieInfoDO(Long id, String movieId, String posterUrl, String name, LocalDate releaseTime, String summary, Double imdbScore, Integer duration, List<DirectorDO> directors, List<WriterDO> writers, List<ActorDO> actors, List<LanguageDO> languages, List<CountryDO> countries, List<MovieTagDO> tags) {
        this.id = id;
        this.movieId = movieId;
        this.posterUrl = posterUrl;
        this.name = name;
        this.releaseTime = releaseTime;
        this.summary = summary;
        this.imdbScore = imdbScore;
        this.duration = duration;
        this.directors = directors;
        this.writers = writers;
        this.actors = actors;
        this.languages = languages;
        this.countries = countries;
        this.tags = tags;
    }
}