package me.newsong.domain.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class WriterDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column writer.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column writer.writer_name
     *
     * @mbggenerated
     */
    private String writerName;
    public WriterDO(String writerName){
        this.writerName = writerName;
    }
}