package me.newsong.dao;

import me.newsong.domain.entity.ActorDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated
     */
    int insert(ActorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated
     */
    int insertSelective(ActorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated
     */
    ActorDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ActorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ActorDO record);
    ActorDO findByName(@Param("name") String name);
    List<ActorDO> findByMovieId(@Param("id")String movieId);
    
}