package me.newsong.dao;

import me.newsong.domain.entity.DirectorDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DirectorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    int insert(DirectorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    int insertSelective(DirectorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    DirectorDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DirectorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table director
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DirectorDO record);
    DirectorDO findByName(@Param("name") String name);
    List<DirectorDO> findByMovieId(@Param("id")String movieId);
    
}