package me.newsong.dao;

import me.newsong.domain.entity.LanguageDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LanguageDOMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int insert(LanguageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int insertSelective(LanguageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    LanguageDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LanguageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table language
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LanguageDO record);
    
    LanguageDO findByName(@Param("name") String name);
    List<LanguageDO> findByMovieId(@Param("id")String movieId);
    
}