package me.newsong.dao;

import me.newsong.domain.entity.MovieWriterKey;
import org.apache.ibatis.annotations.Param;

public interface MovieWriterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_writer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MovieWriterKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_writer
     *
     * @mbggenerated
     */
    int insert(MovieWriterKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_writer
     *
     * @mbggenerated
     */
    int insertSelective(MovieWriterKey record);

    MovieWriterKey findById(@Param("movieId") Long movieId, @Param("writerId") Long writerId);
}