package me.newsong.dao;

import me.newsong.domain.entity.MovieTagDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MovieTagDOMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbggenerated
     */
    int insert(MovieTagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbggenerated
     */
    int insertSelective(MovieTagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbggenerated
     */
    MovieTagDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MovieTagDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MovieTagDO record);
    List<MovieTagDO> findAll();
    MovieTagDO findByName(@Param("name") String name);

    List<MovieTagDO> findByMovieId(@Param("id")String movieId);
    
}