package me.newsong.dao;

import com.github.pagehelper.Page;
import me.newsong.domain.entity.UserDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    UserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDO record);
    
    UserDO findByUserId(@Param("id") String id);
    UserDO findByUserRecommendId(@Param("id") Long id);
    List<UserDO >  findAllDisplay();
    List<UserDO > findAllUnDisplay();
    List<String> findAllNames();
    Page<UserDO> findByNameContaining(@Param("name") String name,@Param("pageNum") int pageNum,@Param("pageSize") int pageSize);
    List<String> findAllUserIds();
    UserDO findByUsername(@Param("username") String username);
}