package me.newsong.dao;

import me.newsong.domain.entity.WriterDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface WriterDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table writer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table writer
     *
     * @mbggenerated
     */
    int insert(WriterDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table writer
     *
     * @mbggenerated
     */
    int insertSelective(WriterDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table writer
     *
     * @mbggenerated
     */
    WriterDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table writer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WriterDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table writer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WriterDO record);

    WriterDO findByName(@Param("name") String name);

    List<WriterDO> findByMovieId(@Param("id") String movieId);
}